Adding Keycloak
civo/kubernetes-marketplace pull request #333
Opened 2022-06-16 06:31 UTC by harsh4870

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot)

2022-06-17 12:58 UTC, saiyam1814 requested changes
Thank you for the PR , 
can you include the required services section in the manifest.yaml file

https://github.com/civo/kubernetes-marketplace/blob/master/traefik2-loadbalancer/manifest.yaml

Also why you are using a Loadbalancer when you have provided the ingress in post install? 
Can you please include the screenshots in the comments and show how its working.

2022-06-20 04:50 UTC, saiyam1814 commented
ping @harsh4870 ^^

2022-06-20 05:19 UTC, harsh4870 commented
@saiyam1814  Hi Saiyam 

thanks for reviewing and sharing suggestions, sure will update the screenshots in the comment with details. 

Kept load balancer in service if anyone wants to access directly over the IP or else can use the Ingress as per need, added ingress for ref.

2022-06-27 07:20 UTC, saiyam1814 commented
> @saiyam1814 Hi Saiyam
> 
> thanks for reviewing and sharing suggestions, sure will update the screenshots in the comment with details.
> 
> Kept load balancer in service if anyone wants to access directly over the IP or else can use the Ingress as per need, added ingress for ref.

Hey @harsh4870 any updates with the screenshots working using the steps that you mentioned in the files in the PR ?

2022-06-27 07:22 UTC, harsh4870 commented
> On it, will be updating it before EOD sorry for the delay.

2022-07-05 07:09 UTC, saiyam1814 commented
HEllo @harsh4870 left a comment for post install. Once you update please ping and I will merge

2022-07-05 07:46 UTC, harsh4870 commented on keycloak/post_install.md
> +## Keycloak
Sure, i have updated the documentation.

2022-07-05 07:47 UTC, harsh4870 commented
@saiyam1814  Sure, thanks, i have added the note and updated the doc.

2022-07-05 10:09 UTC, saiyam1814 commented
LGTM the changes will be live in 15-20 minutes, please do test tin production as well.

2022-07-05 10:09 UTC, merged

2022-07-06 08:43 UTC, saiyam1814 commented
@harsh4870 how do you get the creds for the admin console? anything pointed in the docs can we have that part of post install ?

2022-07-06 08:51 UTC, harsh4870 commented
@saiyam1814  Default id password is admin, admin for keycloak. One we are setting into deployment env. 

```
env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
```

2022-07-06 10:16 UTC, saiyam1814 commented
@harsh4870 you could have used the variables to autogrnerate the passwords. 
Also can you fix post install 
```
[http://selenium/.<your-cluster-id>.[k8s.civo.com](http://k8s.civo.com/)](https://www.keycloak.org/getting-started/getting-started-kube)
```

2022-07-06 10:42 UTC, harsh4870 commented
@saiyam1814  Raised https://github.com/civo/kubernetes-marketplace/pull/340