spinkube: bump to 0.2.0
civo/kubernetes-marketplace pull request #780
Opened 2024-05-21 13:27 UTC by endocrimes

* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal. (@radu-matei / @saiyam1814)
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot).
* [x] Updated the version number of the app if that has changed.

I haven't tested this yet (was testing something else on Civo and remembered we cut a release last week), but I can do so later.

[Changelog](https://github.com/spinkube/spin-operator/releases/tag/v0.2.0), the main new feature being ensuring that SpinApps have TLS certs for outbound connections: https://github.com/spinkube/spin-operator/pull/207

2024-07-02 13:46 UTC, kunal-kushwaha requested changes
@endocrimes can you please check it's working with the updated version and include a screenshot?

2024-07-15 16:13 UTC, kunal-kushwaha approved these changes

2024-07-15 16:13 UTC, kunal-kushwaha requested changes
please resolve merge conflicts

2024-08-14 14:04 UTC, endocrimes commented
Done (also attached a screenshot of 0.2.0 running in a new Talos cluster) 

![image](https://github.com/user-attachments/assets/fe8b9844-82a7-4472-a3dc-0fc163b3599d)

2024-09-07 01:04 UTC, kunal-kushwaha approved these changes

2024-09-07 01:05 UTC, merged